### ISSUE TITLE
Cannot open raw file in NC 28

### ISSUE THREAD

**Issue by faznam** [ariselseng/camerarawpreviews#102] opened 2024-01-12 12:57 UTC
I can't open a raw file. In the file list view, the browser downloads the raw file directly, and in the grid view, clicking on a file does nothing at all.
However, the thumbnails are generated and displayed correctly.

Infos :
Camera RAW Previews 0.8.4
Nextcloud 28.0.1

**Comment by ikocev** [comment] 2024-01-28 09:46
+1

**Comment by berveles** [comment] 2024-02-03 13:54
Similar situation

**Comment by eatgrass** [comment] 2024-03-07 01:11
same

**Comment by sebastianfru** [comment] 2024-03-22 13:07
Same

**Comment by ariselseng** [comment] 2024-05-19 10:07
This is a duplicate of this one: https://github.com/ariselseng/camerarawpreviews/issues/99

**Closed by ariselseng** 2024-05-19 10:07 UTC
